---
language: ruby
sudo: false
cache: bundler
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - bundle exec rake test_app
script:
  - bundle exec rspec spec
rvm:
  - 2.2.4
  - 2.3.0
